#test execution script.

language: scala
jdk:
  - oraclejdk8

sudo: false
before_install: umask 0022
scala:
  - 2.10.4
  - 2.11.7
script:
- "echo no op"

# whitelist
branches:
  only:
    - master
    - develop